services:
  - type: web
    name: edas-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true

  - type: static
    name: edas-frontend
    buildCommand: cd app && npm install && npm run build
    staticPublishPath: app/build