services:
  - type: web
    name: edas-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    workingDir: backend

staticSites:
  - name: edas-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    workingDir: app/Admin
    env: node
