services:
  - type: web
    name: edas-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

staticSites:
  - name: edas-frontend
    region: oregon
    plan: free
    buildCommand: cd app && npm install && npm run build
    staticPublishPath: app/build
    pullRequestPreviewsEnabled: true